import ReactMarkdown from "react-markdown"
import Moment from "react-moment"
import { fetchAPI } from "../../lib/api"
import Layout from "../../components/layout"
import NextImage from "../../components/image"
import Seo from "../../components/seo"
import { getStrapiMedia } from "../../lib/media"
import Footer from "../../components/footer"

const Cover = ({ post, image }) => {
  return (
    <div className="cover-image">
      <div className="background-container">
        <NextImage image={image} />
      </div>
      
      <div className="foreground-container">
        <h1 className="boom">{post.attributes.title}</h1>
        <h1>{post.attributes.subtitle}</h1>
      </div>
    </div>
  )
}

const Breadcrumbs = ({ post }) => {
  return (
    <div className="post-breadcrumbs">
      Breadcrumb
    </div>
  );
}

const Meta = ({ post }) => {
  return (
    <div className="post-meta">
      Meta
    </div>
  );
}

const Body = ({ post }) => {
  return (
    <div className="post-body-content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget fringilla turpis. Nam ac tempor diam, ac condimentum sem. Quisque sodales vestibulum leo fringilla facilisis. Sed tristique, ante ac dignissim faucibus, nunc massa porttitor nisl, ac aliquam leo mi non dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris quis dictum purus. Aliquam id vestibulum mauris.<br /><br />
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porttitor efficitur pharetra. Aenean sapien metus, fringilla a risus eu, cursus lobortis dui. Vivamus elementum interdum ipsum eu porta. Donec et ipsum sed sem tempus porta a ac magna. Ut quis mi quis dolor vestibulum viverra ut at erat. Nunc vitae quam felis. Suspendisse rutrum lobortis semper. Pellentesque nec massa eu mauris finibus dignissim id a nulla. Nunc quis nulla lectus. Fusce at leo nec nunc facilisis ultrices. Duis maximus lobortis odio ut vulputate. Nunc feugiat dapibus nunc a viverra.<br /><br />
      Suspendisse congue sagittis orci nec venenatis. Praesent ex libero, tincidunt vitae velit non, dignissim fermentum augue. Suspendisse in magna sagittis, condimentum eros vitae, consequat turpis. In id mi mauris. Integer congue sodales quam. Nunc volutpat eros neque, vel malesuada odio pretium at. Maecenas eu orci nunc. Sed non lacus sem. Sed at dolor eu diam suscipit fringilla.<br /><br />
      Morbi varius lorem vel rutrum ullamcorper. Cras iaculis cursus pretium. In id est ut ex venenatis dictum id ut mauris. Nullam tempor id neque id rhoncus. Pellentesque a tristique nisl. Suspendisse laoreet, leo vel sagittis cursus, nunc est placerat sapien, id cursus lorem dolor at tellus. Aliquam eu velit vel neque pellentesque convallis. Nam mollis sem a arcu facilisis rutrum. Aenean tempor vel felis et congue. Integer pulvinar blandit mattis.<br /><br />
      Aliquam sagittis lacus volutpat massa semper, sit amet mattis nunc varius. Fusce ultrices nisi sit amet dui hendrerit bibendum. Sed et dolor quis tellus consequat ultrices. Ut placerat lacinia ligula et tristique. Suspendisse aliquet tortor sed eros vestibulum lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer laoreet porttitor urna, ut semper est dictum eu.<br /><br />
      Phasellus dignissim lectus ut risus vehicula vestibulum. Maecenas scelerisque felis quis tempus scelerisque. Vivamus ut elit ligula. Integer rutrum odio sit amet semper bibendum. Phasellus sapien turpis, fermentum id hendrerit mollis, dapibus id mi. Integer sagittis, risus vitae tincidunt placerat, felis felis maximus velit, nec suscipit ligula odio non nisi. Pellentesque fermentum interdum metus, accumsan laoreet nulla aliquam sed. Nullam ac ipsum ultricies elit malesuada malesuada eu quis velit. Nunc ultricies metus lorem, eget tincidunt justo sollicitudin a. Pellentesque sed fermentum dolor. Cras id quam tempus, sagittis neque dictum, ultricies mauris. Donec auctor scelerisque diam, eu porta risus malesuada in. Vivamus sed purus sit amet massa eleifend dapibus. Donec sagittis, odio eget posuere pretium, tellus lacus mollis ex, id iaculis leo est in dolor. Nunc dictum ex mauris, in mattis justo vulputate id. Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br /><br />
      Curabitur quis ex eget mauris fermentum semper. In hac habitasse platea dictumst. Suspendisse mollis nisl vel lectus posuere, ac elementum nunc rutrum. Morbi varius eu turpis ut aliquam. Donec feugiat lacus erat, ut bibendum justo dapibus nec. Vestibulum metus quam, efficitur eget nisi non, placerat cursus nisi. Integer orci odio, interdum sed augue sit amet, scelerisque congue dui. Nam venenatis ex nec ligula fermentum sodales. Praesent ac felis a libero commodo lacinia. Curabitur sit amet fermentum diam, sit amet tristique eros. Etiam molestie placerat ex ut posuere. Praesent pellentesque lacus a fringilla lacinia. Integer velit metus, ultrices sit amet nunc at, maximus auctor turpis. Cras non neque non urna faucibus varius.<br /><br />
      Nam consequat dictum congue. Aliquam lorem ligula, porta in urna in, porttitor ornare massa. Pellentesque facilisis pellentesque est, quis facilisis ipsum scelerisque eget. Quisque et augue efficitur, aliquam quam vel, ultricies leo. Fusce consequat orci elit, sit amet mattis dolor consequat vel. Nunc scelerisque, leo eu bibendum consequat, purus diam imperdiet enim, a egestas magna lorem facilisis nulla. Aliquam tristique purus vitae fringilla tristique. Integer tincidunt augue vel risus ullamcorper, volutpat vehicula mi scelerisque. Maecenas non mattis ante.<br /><br />
      Aliquam ipsum dolor, vestibulum a egestas non, rutrum a turpis. Ut nec dictum eros, efficitur semper velit. Nam mattis felis et hendrerit accumsan. Donec tincidunt turpis et euismod mollis. Aliquam vehicula nec ligula quis euismod. Proin pulvinar gravida euismod. Morbi sollicitudin semper diam, nec imperdiet ipsum cursus sed. In non quam magna. Aenean eget felis sodales, sodales ligula ac, venenatis nunc.<br /><br />
      Vestibulum eleifend ac nibh mattis pulvinar. Ut blandit tempor leo, a hendrerit quam mollis non. Fusce venenatis velit vitae ligula convallis tincidunt. Sed dapibus consequat turpis eu maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In et nibh velit. Integer venenatis id eros ut fermentum. Curabitur volutpat urna ac nisi accumsan, a cursus nisl euismod. Maecenas et ex id orci dapibus dictum nec quis ipsum. Morbi pulvinar odio ac mauris accumsan, id scelerisque leo commodo. Suspendisse metus ex, malesuada nec quam ut, condimentum lacinia massa. Morbi sollicitudin efficitur nisi, non eleifend ligula consectetur eget. In suscipit lorem quis ligula ultricies consequat. Vivamus at sodales risus, sed iaculis felis.<br /><br />
      Pellentesque magna felis, malesuada id aliquam quis, tincidunt eu nulla. Integer pharetra congue placerat. Aliquam erat volutpat. Aliquam blandit aliquet pharetra. Nam tristique erat eros, in ultrices nulla rutrum sit amet. Vestibulum tortor erat, vestibulum quis aliquet vel, lacinia sit amet nisi. Duis sapien sapien, aliquet vitae erat et, gravida auctor sem. Curabitur vitae congue tortor. Aliquam efficitur sollicitudin mi mattis consequat. Quisque faucibus, sem sed vehicula lobortis, quam arcu interdum erat, non finibus enim tortor egestas erat.<br /><br />
      Morbi eros elit, blandit sit amet commodo at, laoreet non lectus. Vestibulum porta, urna ac porttitor dictum, eros arcu maximus ipsum, sed euismod neque nunc eget ligula. Vestibulum tincidunt tortor urna, sit amet rhoncus sapien feugiat fringilla. Sed blandit gravida quam, et consequat nisi euismod auctor. Nullam accumsan volutpat dolor non dictum. Quisque congue, elit non pharetra dictum, purus magna bibendum dui, a lacinia est leo eu nisl. Aenean vitae dolor elit. Fusce et arcu vitae neque ultrices accumsan ut sit amet leo.<br /><br />
      Nunc id placerat ante. Maecenas consequat eu nulla quis facilisis. Donec justo lectus, varius vel hendrerit et, pharetra nec libero. Cras neque libero, pulvinar eget imperdiet non, posuere at nibh. Cras ultrices molestie vestibulum. Nunc vulputate ut purus non cursus. Etiam ut sem placerat, tristique erat ornare, malesuada diam. Mauris vitae sapien facilisis, egestas libero ut, convallis nisl. Fusce metus lorem, consequat vulputate sem at, sodales luctus tortor. Maecenas tincidunt placerat metus id venenatis. In ornare tortor eget magna lobortis vestibulum. Ut bibendum ligula enim, ut elementum elit blandit ut. Phasellus tincidunt placerat libero vel cursus. Nulla laoreet, libero non maximus sollicitudin, enim ligula gravida arcu, ut semper metus nisi sit amet ante.<br /><br />
      Phasellus semper leo lorem, ac semper mauris varius eget. Vestibulum mollis purus non quam laoreet sodales. Donec et molestie mauris. Vivamus interdum nibh aliquet, rhoncus nisl egestas, placerat eros. Pellentesque aliquet, urna a rutrum egestas, ex justo venenatis nulla, non tristique nisl augue non ante. Nullam gravida a risus quis finibus. Nullam tellus metus, vehicula a massa eget, lacinia facilisis metus. Morbi dictum neque in turpis aliquam feugiat. Nulla volutpat dui non libero finibus congue. Sed in sapien rutrum, hendrerit erat ut, cursus purus. Aliquam erat volutpat. In at dignissim nisi. Suspendisse potenti. Pellentesque a imperdiet dolor.<br /><br />
      Pellentesque eu urna elit. Vestibulum molestie quis elit nec imperdiet. Ut eu elit nec nisl eleifend cursus tempus vel augue. Aliquam consectetur elementum iaculis. Pellentesque eleifend, sapien eu tincidunt molestie, augue turpis dictum risus, sit amet sodales diam mauris vitae diam. Maecenas id mattis sapien, sed dictum lorem. Suspendisse malesuada vel nisl nec semper. Suspendisse pellentesque fermentum massa, vel maximus arcu gravida vel. Nullam sodales metus non diam commodo vulputate. Cras porta rhoncus lacus. Phasellus sit amet risus at diam dignissim suscipit. Integer convallis turpis quis est mollis, et efficitur est sagittis. Cras laoreet bibendum felis eu rutrum. Quisque consequat sollicitudin tellus, vel cursus elit ornare vitae.<br /><br />
      Suspendisse id porta tellus, eget luctus nisl. Mauris viverra consectetur scelerisque. Mauris gravida velit pulvinar, cursus nunc porta, molestie sapien. Duis pharetra odio et fringilla aliquet. Nulla blandit lectus a metus facilisis, sed gravida tortor consectetur. Morbi facilisis sed sem ut malesuada. Sed quis ullamcorper arcu. Integer rhoncus lorem sodales, sagittis mi a, accumsan turpis. Aliquam eleifend eleifend ornare. Sed elementum, libero fringilla volutpat molestie, tellus lacus sodales massa, at facilisis diam metus a lacus. Mauris non convallis orci. Nam sit amet leo odio. Nullam id consequat mi, cursus commodo arcu. Nunc sed elit vitae est tincidunt elementum.<br /><br />
      Fusce dignissim eros lacus, vel vestibulum arcu sagittis vel. Nullam eget tortor nec orci faucibus lacinia. In venenatis sem eget sem maximus dignissim. Cras dignissim eu sapien eget porttitor. In blandit nibh nec dolor rutrum sagittis. Phasellus maximus egestas facilisis. Morbi quis neque sit amet odio tincidunt blandit.<br /><br />
      Vestibulum imperdiet non velit in imperdiet. Aliquam consequat est quis mauris bibendum consectetur. Pellentesque convallis et quam ut imperdiet. Nullam tristique pellentesque scelerisque. In convallis lectus non risus ornare, sit amet egestas ipsum vulputate. Curabitur eros ligula, tempus eget vehicula a, malesuada ac ipsum. Vivamus pulvinar lectus tellus, eu pellentesque elit tincidunt id. Vivamus varius nibh cursus ipsum lacinia, eget cursus quam faucibus. Phasellus in nisl vitae metus dignissim semper. Etiam molestie, augue ut vestibulum sollicitudin, lorem leo auctor lectus, nec rhoncus neque tortor ac nisi. Vivamus at finibus augue, facilisis tempor odio. Curabitur nisi quam, dictum sit amet arcu non, semper dignissim dui.<br /><br />
      Sed id maximus enim. Mauris pretium pharetra arcu, eu maximus sapien auctor id. Mauris hendrerit tellus in purus volutpat laoreet. Donec sed ligula eu dolor varius consequat. Maecenas justo mauris, pulvinar quis interdum et, congue quis sapien. Vivamus porta libero risus. Morbi at ultrices ligula. Sed quis velit est. Mauris efficitur massa vitae ipsum imperdiet, sit amet hendrerit dui sagittis. Proin vitae ultrices dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed aliquam velit ut nisl tincidunt luctus. Curabitur elit justo, gravida mollis aliquam sit amet, pharetra nec turpis. Vestibulum eu cursus magna. Pellentesque sagittis interdum velit, id congue elit sagittis sit amet.<br /><br />
      Mauris vel neque vestibulum, molestie dui sed, tempor magna. Vestibulum interdum accumsan erat ut faucibus. Donec consectetur lacinia urna, id molestie magna porttitor in. Maecenas dignissim ante sed massa aliquet, lobortis scelerisque mauris tempor. Suspendisse nulla mi, eleifend at massa vitae, aliquet commodo velit. Proin egestas imperdiet diam, venenatis gravida justo pulvinar id. Sed sit amet sem id nulla rutrum pretium. Etiam id ipsum aliquam felis iaculis luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer ultricies vitae turpis vitae auctor. Duis pulvinar velit sed lacinia tincidunt.<br /><br />
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget fringilla turpis. Nam ac tempor diam, ac condimentum sem. Quisque sodales vestibulum leo fringilla facilisis. Sed tristique, ante ac dignissim faucibus, nunc massa porttitor nisl, ac aliquam leo mi non dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris quis dictum purus. Aliquam id vestibulum mauris.<br /><br />
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porttitor efficitur pharetra. Aenean sapien metus, fringilla a risus eu, cursus lobortis dui. Vivamus elementum interdum ipsum eu porta. Donec et ipsum sed sem tempus porta a ac magna. Ut quis mi quis dolor vestibulum viverra ut at erat. Nunc vitae quam felis. Suspendisse rutrum lobortis semper. Pellentesque nec massa eu mauris finibus dignissim id a nulla. Nunc quis nulla lectus. Fusce at leo nec nunc facilisis ultrices. Duis maximus lobortis odio ut vulputate. Nunc feugiat dapibus nunc a viverra.<br /><br />
      Suspendisse congue sagittis orci nec venenatis. Praesent ex libero, tincidunt vitae velit non, dignissim fermentum augue. Suspendisse in magna sagittis, condimentum eros vitae, consequat turpis. In id mi mauris. Integer congue sodales quam. Nunc volutpat eros neque, vel malesuada odio pretium at. Maecenas eu orci nunc. Sed non lacus sem. Sed at dolor eu diam suscipit fringilla.<br /><br />
      Morbi varius lorem vel rutrum ullamcorper. Cras iaculis cursus pretium. In id est ut ex venenatis dictum id ut mauris. Nullam tempor id neque id rhoncus. Pellentesque a tristique nisl. Suspendisse laoreet, leo vel sagittis cursus, nunc est placerat sapien, id cursus lorem dolor at tellus. Aliquam eu velit vel neque pellentesque convallis. Nam mollis sem a arcu facilisis rutrum. Aenean tempor vel felis et congue. Integer pulvinar blandit mattis.<br /><br />
      Aliquam sagittis lacus volutpat massa semper, sit amet mattis nunc varius. Fusce ultrices nisi sit amet dui hendrerit bibendum. Sed et dolor quis tellus consequat ultrices. Ut placerat lacinia ligula et tristique. Suspendisse aliquet tortor sed eros vestibulum lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer laoreet porttitor urna, ut semper est dictum eu.<br /><br />
      Phasellus dignissim lectus ut risus vehicula vestibulum. Maecenas scelerisque felis quis tempus scelerisque. Vivamus ut elit ligula. Integer rutrum odio sit amet semper bibendum. Phasellus sapien turpis, fermentum id hendrerit mollis, dapibus id mi. Integer sagittis, risus vitae tincidunt placerat, felis felis maximus velit, nec suscipit ligula odio non nisi. Pellentesque fermentum interdum metus, accumsan laoreet nulla aliquam sed. Nullam ac ipsum ultricies elit malesuada malesuada eu quis velit. Nunc ultricies metus lorem, eget tincidunt justo sollicitudin a. Pellentesque sed fermentum dolor. Cras id quam tempus, sagittis neque dictum, ultricies mauris. Donec auctor scelerisque diam, eu porta risus malesuada in. Vivamus sed purus sit amet massa eleifend dapibus. Donec sagittis, odio eget posuere pretium, tellus lacus mollis ex, id iaculis leo est in dolor. Nunc dictum ex mauris, in mattis justo vulputate id. Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br /><br />
      Curabitur quis ex eget mauris fermentum semper. In hac habitasse platea dictumst. Suspendisse mollis nisl vel lectus posuere, ac elementum nunc rutrum. Morbi varius eu turpis ut aliquam. Donec feugiat lacus erat, ut bibendum justo dapibus nec. Vestibulum metus quam, efficitur eget nisi non, placerat cursus nisi. Integer orci odio, interdum sed augue sit amet, scelerisque congue dui. Nam venenatis ex nec ligula fermentum sodales. Praesent ac felis a libero commodo lacinia. Curabitur sit amet fermentum diam, sit amet tristique eros. Etiam molestie placerat ex ut posuere. Praesent pellentesque lacus a fringilla lacinia. Integer velit metus, ultrices sit amet nunc at, maximus auctor turpis. Cras non neque non urna faucibus varius.<br /><br />
      Nam consequat dictum congue. Aliquam lorem ligula, porta in urna in, porttitor ornare massa. Pellentesque facilisis pellentesque est, quis facilisis ipsum scelerisque eget. Quisque et augue efficitur, aliquam quam vel, ultricies leo. Fusce consequat orci elit, sit amet mattis dolor consequat vel. Nunc scelerisque, leo eu bibendum consequat, purus diam imperdiet enim, a egestas magna lorem facilisis nulla. Aliquam tristique purus vitae fringilla tristique. Integer tincidunt augue vel risus ullamcorper, volutpat vehicula mi scelerisque. Maecenas non mattis ante.<br /><br />
      Aliquam ipsum dolor, vestibulum a egestas non, rutrum a turpis. Ut nec dictum eros, efficitur semper velit. Nam mattis felis et hendrerit accumsan. Donec tincidunt turpis et euismod mollis. Aliquam vehicula nec ligula quis euismod. Proin pulvinar gravida euismod. Morbi sollicitudin semper diam, nec imperdiet ipsum cursus sed. In non quam magna. Aenean eget felis sodales, sodales ligula ac, venenatis nunc.<br /><br />
      Vestibulum eleifend ac nibh mattis pulvinar. Ut blandit tempor leo, a hendrerit quam mollis non. Fusce venenatis velit vitae ligula convallis tincidunt. Sed dapibus consequat turpis eu maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In et nibh velit. Integer venenatis id eros ut fermentum. Curabitur volutpat urna ac nisi accumsan, a cursus nisl euismod. Maecenas et ex id orci dapibus dictum nec quis ipsum. Morbi pulvinar odio ac mauris accumsan, id scelerisque leo commodo. Suspendisse metus ex, malesuada nec quam ut, condimentum lacinia massa. Morbi sollicitudin efficitur nisi, non eleifend ligula consectetur eget. In suscipit lorem quis ligula ultricies consequat. Vivamus at sodales risus, sed iaculis felis.<br /><br />
      Pellentesque magna felis, malesuada id aliquam quis, tincidunt eu nulla. Integer pharetra congue placerat. Aliquam erat volutpat. Aliquam blandit aliquet pharetra. Nam tristique erat eros, in ultrices nulla rutrum sit amet. Vestibulum tortor erat, vestibulum quis aliquet vel, lacinia sit amet nisi. Duis sapien sapien, aliquet vitae erat et, gravida auctor sem. Curabitur vitae congue tortor. Aliquam efficitur sollicitudin mi mattis consequat. Quisque faucibus, sem sed vehicula lobortis, quam arcu interdum erat, non finibus enim tortor egestas erat.<br /><br />
      Morbi eros elit, blandit sit amet commodo at, laoreet non lectus. Vestibulum porta, urna ac porttitor dictum, eros arcu maximus ipsum, sed euismod neque nunc eget ligula. Vestibulum tincidunt tortor urna, sit amet rhoncus sapien feugiat fringilla. Sed blandit gravida quam, et consequat nisi euismod auctor. Nullam accumsan volutpat dolor non dictum. Quisque congue, elit non pharetra dictum, purus magna bibendum dui, a lacinia est leo eu nisl. Aenean vitae dolor elit. Fusce et arcu vitae neque ultrices accumsan ut sit amet leo.<br /><br />
      Nunc id placerat ante. Maecenas consequat eu nulla quis facilisis. Donec justo lectus, varius vel hendrerit et, pharetra nec libero. Cras neque libero, pulvinar eget imperdiet non, posuere at nibh. Cras ultrices molestie vestibulum. Nunc vulputate ut purus non cursus. Etiam ut sem placerat, tristique erat ornare, malesuada diam. Mauris vitae sapien facilisis, egestas libero ut, convallis nisl. Fusce metus lorem, consequat vulputate sem at, sodales luctus tortor. Maecenas tincidunt placerat metus id venenatis. In ornare tortor eget magna lobortis vestibulum. Ut bibendum ligula enim, ut elementum elit blandit ut. Phasellus tincidunt placerat libero vel cursus. Nulla laoreet, libero non maximus sollicitudin, enim ligula gravida arcu, ut semper metus nisi sit amet ante.<br /><br />
      Phasellus semper leo lorem, ac semper mauris varius eget. Vestibulum mollis purus non quam laoreet sodales. Donec et molestie mauris. Vivamus interdum nibh aliquet, rhoncus nisl egestas, placerat eros. Pellentesque aliquet, urna a rutrum egestas, ex justo venenatis nulla, non tristique nisl augue non ante. Nullam gravida a risus quis finibus. Nullam tellus metus, vehicula a massa eget, lacinia facilisis metus. Morbi dictum neque in turpis aliquam feugiat. Nulla volutpat dui non libero finibus congue. Sed in sapien rutrum, hendrerit erat ut, cursus purus. Aliquam erat volutpat. In at dignissim nisi. Suspendisse potenti. Pellentesque a imperdiet dolor.<br /><br />
      Pellentesque eu urna elit. Vestibulum molestie quis elit nec imperdiet. Ut eu elit nec nisl eleifend cursus tempus vel augue. Aliquam consectetur elementum iaculis. Pellentesque eleifend, sapien eu tincidunt molestie, augue turpis dictum risus, sit amet sodales diam mauris vitae diam. Maecenas id mattis sapien, sed dictum lorem. Suspendisse malesuada vel nisl nec semper. Suspendisse pellentesque fermentum massa, vel maximus arcu gravida vel. Nullam sodales metus non diam commodo vulputate. Cras porta rhoncus lacus. Phasellus sit amet risus at diam dignissim suscipit. Integer convallis turpis quis est mollis, et efficitur est sagittis. Cras laoreet bibendum felis eu rutrum. Quisque consequat sollicitudin tellus, vel cursus elit ornare vitae.<br /><br />
      Suspendisse id porta tellus, eget luctus nisl. Mauris viverra consectetur scelerisque. Mauris gravida velit pulvinar, cursus nunc porta, molestie sapien. Duis pharetra odio et fringilla aliquet. Nulla blandit lectus a metus facilisis, sed gravida tortor consectetur. Morbi facilisis sed sem ut malesuada. Sed quis ullamcorper arcu. Integer rhoncus lorem sodales, sagittis mi a, accumsan turpis. Aliquam eleifend eleifend ornare. Sed elementum, libero fringilla volutpat molestie, tellus lacus sodales massa, at facilisis diam metus a lacus. Mauris non convallis orci. Nam sit amet leo odio. Nullam id consequat mi, cursus commodo arcu. Nunc sed elit vitae est tincidunt elementum.<br /><br />
      Fusce dignissim eros lacus, vel vestibulum arcu sagittis vel. Nullam eget tortor nec orci faucibus lacinia. In venenatis sem eget sem maximus dignissim. Cras dignissim eu sapien eget porttitor. In blandit nibh nec dolor rutrum sagittis. Phasellus maximus egestas facilisis. Morbi quis neque sit amet odio tincidunt blandit.<br /><br />
      Vestibulum imperdiet non velit in imperdiet. Aliquam consequat est quis mauris bibendum consectetur. Pellentesque convallis et quam ut imperdiet. Nullam tristique pellentesque scelerisque. In convallis lectus non risus ornare, sit amet egestas ipsum vulputate. Curabitur eros ligula, tempus eget vehicula a, malesuada ac ipsum. Vivamus pulvinar lectus tellus, eu pellentesque elit tincidunt id. Vivamus varius nibh cursus ipsum lacinia, eget cursus quam faucibus. Phasellus in nisl vitae metus dignissim semper. Etiam molestie, augue ut vestibulum sollicitudin, lorem leo auctor lectus, nec rhoncus neque tortor ac nisi. Vivamus at finibus augue, facilisis tempor odio. Curabitur nisi quam, dictum sit amet arcu non, semper dignissim dui.<br /><br />
      Sed id maximus enim. Mauris pretium pharetra arcu, eu maximus sapien auctor id. Mauris hendrerit tellus in purus volutpat laoreet. Donec sed ligula eu dolor varius consequat. Maecenas justo mauris, pulvinar quis interdum et, congue quis sapien. Vivamus porta libero risus. Morbi at ultrices ligula. Sed quis velit est. Mauris efficitur massa vitae ipsum imperdiet, sit amet hendrerit dui sagittis. Proin vitae ultrices dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed aliquam velit ut nisl tincidunt luctus. Curabitur elit justo, gravida mollis aliquam sit amet, pharetra nec turpis. Vestibulum eu cursus magna. Pellentesque sagittis interdum velit, id congue elit sagittis sit amet.<br /><br />
      Mauris vel neque vestibulum, molestie dui sed, tempor magna. Vestibulum interdum accumsan erat ut faucibus. Donec consectetur lacinia urna, id molestie magna porttitor in. Maecenas dignissim ante sed massa aliquet, lobortis scelerisque mauris tempor. Suspendisse nulla mi, eleifend at massa vitae, aliquet commodo velit. Proin egestas imperdiet diam, venenatis gravida justo pulvinar id. Sed sit amet sem id nulla rutrum pretium. Etiam id ipsum aliquam felis iaculis luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer ultricies vitae turpis vitae auctor. Duis pulvinar velit sed lacinia tincidunt.<br /><br />
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget fringilla turpis. Nam ac tempor diam, ac condimentum sem. Quisque sodales vestibulum leo fringilla facilisis. Sed tristique, ante ac dignissim faucibus, nunc massa porttitor nisl, ac aliquam leo mi non dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris quis dictum purus. Aliquam id vestibulum mauris.<br /><br />
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porttitor efficitur pharetra. Aenean sapien metus, fringilla a risus eu, cursus lobortis dui. Vivamus elementum interdum ipsum eu porta. Donec et ipsum sed sem tempus porta a ac magna. Ut quis mi quis dolor vestibulum viverra ut at erat. Nunc vitae quam felis. Suspendisse rutrum lobortis semper. Pellentesque nec massa eu mauris finibus dignissim id a nulla. Nunc quis nulla lectus. Fusce at leo nec nunc facilisis ultrices. Duis maximus lobortis odio ut vulputate. Nunc feugiat dapibus nunc a viverra.<br /><br />
      Suspendisse congue sagittis orci nec venenatis. Praesent ex libero, tincidunt vitae velit non, dignissim fermentum augue. Suspendisse in magna sagittis, condimentum eros vitae, consequat turpis. In id mi mauris. Integer congue sodales quam. Nunc volutpat eros neque, vel malesuada odio pretium at. Maecenas eu orci nunc. Sed non lacus sem. Sed at dolor eu diam suscipit fringilla.<br /><br />
      Morbi varius lorem vel rutrum ullamcorper. Cras iaculis cursus pretium. In id est ut ex venenatis dictum id ut mauris. Nullam tempor id neque id rhoncus. Pellentesque a tristique nisl. Suspendisse laoreet, leo vel sagittis cursus, nunc est placerat sapien, id cursus lorem dolor at tellus. Aliquam eu velit vel neque pellentesque convallis. Nam mollis sem a arcu facilisis rutrum. Aenean tempor vel felis et congue. Integer pulvinar blandit mattis.<br /><br />
      Aliquam sagittis lacus volutpat massa semper, sit amet mattis nunc varius. Fusce ultrices nisi sit amet dui hendrerit bibendum. Sed et dolor quis tellus consequat ultrices. Ut placerat lacinia ligula et tristique. Suspendisse aliquet tortor sed eros vestibulum lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer laoreet porttitor urna, ut semper est dictum eu.<br /><br />
      Phasellus dignissim lectus ut risus vehicula vestibulum. Maecenas scelerisque felis quis tempus scelerisque. Vivamus ut elit ligula. Integer rutrum odio sit amet semper bibendum. Phasellus sapien turpis, fermentum id hendrerit mollis, dapibus id mi. Integer sagittis, risus vitae tincidunt placerat, felis felis maximus velit, nec suscipit ligula odio non nisi. Pellentesque fermentum interdum metus, accumsan laoreet nulla aliquam sed. Nullam ac ipsum ultricies elit malesuada malesuada eu quis velit. Nunc ultricies metus lorem, eget tincidunt justo sollicitudin a. Pellentesque sed fermentum dolor. Cras id quam tempus, sagittis neque dictum, ultricies mauris. Donec auctor scelerisque diam, eu porta risus malesuada in. Vivamus sed purus sit amet massa eleifend dapibus. Donec sagittis, odio eget posuere pretium, tellus lacus mollis ex, id iaculis leo est in dolor. Nunc dictum ex mauris, in mattis justo vulputate id. Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br /><br />
      Curabitur quis ex eget mauris fermentum semper. In hac habitasse platea dictumst. Suspendisse mollis nisl vel lectus posuere, ac elementum nunc rutrum. Morbi varius eu turpis ut aliquam. Donec feugiat lacus erat, ut bibendum justo dapibus nec. Vestibulum metus quam, efficitur eget nisi non, placerat cursus nisi. Integer orci odio, interdum sed augue sit amet, scelerisque congue dui. Nam venenatis ex nec ligula fermentum sodales. Praesent ac felis a libero commodo lacinia. Curabitur sit amet fermentum diam, sit amet tristique eros. Etiam molestie placerat ex ut posuere. Praesent pellentesque lacus a fringilla lacinia. Integer velit metus, ultrices sit amet nunc at, maximus auctor turpis. Cras non neque non urna faucibus varius.<br /><br />
      Nam consequat dictum congue. Aliquam lorem ligula, porta in urna in, porttitor ornare massa. Pellentesque facilisis pellentesque est, quis facilisis ipsum scelerisque eget. Quisque et augue efficitur, aliquam quam vel, ultricies leo. Fusce consequat orci elit, sit amet mattis dolor consequat vel. Nunc scelerisque, leo eu bibendum consequat, purus diam imperdiet enim, a egestas magna lorem facilisis nulla. Aliquam tristique purus vitae fringilla tristique. Integer tincidunt augue vel risus ullamcorper, volutpat vehicula mi scelerisque. Maecenas non mattis ante.<br /><br />
      Aliquam ipsum dolor, vestibulum a egestas non, rutrum a turpis. Ut nec dictum eros, efficitur semper velit. Nam mattis felis et hendrerit accumsan. Donec tincidunt turpis et euismod mollis. Aliquam vehicula nec ligula quis euismod. Proin pulvinar gravida euismod. Morbi sollicitudin semper diam, nec imperdiet ipsum cursus sed. In non quam magna. Aenean eget felis sodales, sodales ligula ac, venenatis nunc.<br /><br />
      Vestibulum eleifend ac nibh mattis pulvinar. Ut blandit tempor leo, a hendrerit quam mollis non. Fusce venenatis velit vitae ligula convallis tincidunt. Sed dapibus consequat turpis eu maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In et nibh velit. Integer venenatis id eros ut fermentum. Curabitur volutpat urna ac nisi accumsan, a cursus nisl euismod. Maecenas et ex id orci dapibus dictum nec quis ipsum. Morbi pulvinar odio ac mauris accumsan, id scelerisque leo commodo. Suspendisse metus ex, malesuada nec quam ut, condimentum lacinia massa. Morbi sollicitudin efficitur nisi, non eleifend ligula consectetur eget. In suscipit lorem quis ligula ultricies consequat. Vivamus at sodales risus, sed iaculis felis.<br /><br />
      Pellentesque magna felis, malesuada id aliquam quis, tincidunt eu nulla. Integer pharetra congue placerat. Aliquam erat volutpat. Aliquam blandit aliquet pharetra. Nam tristique erat eros, in ultrices nulla rutrum sit amet. Vestibulum tortor erat, vestibulum quis aliquet vel, lacinia sit amet nisi. Duis sapien sapien, aliquet vitae erat et, gravida auctor sem. Curabitur vitae congue tortor. Aliquam efficitur sollicitudin mi mattis consequat. Quisque faucibus, sem sed vehicula lobortis, quam arcu interdum erat, non finibus enim tortor egestas erat.<br /><br />
      Morbi eros elit, blandit sit amet commodo at, laoreet non lectus. Vestibulum porta, urna ac porttitor dictum, eros arcu maximus ipsum, sed euismod neque nunc eget ligula. Vestibulum tincidunt tortor urna, sit amet rhoncus sapien feugiat fringilla. Sed blandit gravida quam, et consequat nisi euismod auctor. Nullam accumsan volutpat dolor non dictum. Quisque congue, elit non pharetra dictum, purus magna bibendum dui, a lacinia est leo eu nisl. Aenean vitae dolor elit. Fusce et arcu vitae neque ultrices accumsan ut sit amet leo.<br /><br />
      Nunc id placerat ante. Maecenas consequat eu nulla quis facilisis. Donec justo lectus, varius vel hendrerit et, pharetra nec libero. Cras neque libero, pulvinar eget imperdiet non, posuere at nibh. Cras ultrices molestie vestibulum. Nunc vulputate ut purus non cursus. Etiam ut sem placerat, tristique erat ornare, malesuada diam. Mauris vitae sapien facilisis, egestas libero ut, convallis nisl. Fusce metus lorem, consequat vulputate sem at, sodales luctus tortor. Maecenas tincidunt placerat metus id venenatis. In ornare tortor eget magna lobortis vestibulum. Ut bibendum ligula enim, ut elementum elit blandit ut. Phasellus tincidunt placerat libero vel cursus. Nulla laoreet, libero non maximus sollicitudin, enim ligula gravida arcu, ut semper metus nisi sit amet ante.<br /><br />
      Phasellus semper leo lorem, ac semper mauris varius eget. Vestibulum mollis purus non quam laoreet sodales. Donec et molestie mauris. Vivamus interdum nibh aliquet, rhoncus nisl egestas, placerat eros. Pellentesque aliquet, urna a rutrum egestas, ex justo venenatis nulla, non tristique nisl augue non ante. Nullam gravida a risus quis finibus. Nullam tellus metus, vehicula a massa eget, lacinia facilisis metus. Morbi dictum neque in turpis aliquam feugiat. Nulla volutpat dui non libero finibus congue. Sed in sapien rutrum, hendrerit erat ut, cursus purus. Aliquam erat volutpat. In at dignissim nisi. Suspendisse potenti. Pellentesque a imperdiet dolor.<br /><br />
      Pellentesque eu urna elit. Vestibulum molestie quis elit nec imperdiet. Ut eu elit nec nisl eleifend cursus tempus vel augue. Aliquam consectetur elementum iaculis. Pellentesque eleifend, sapien eu tincidunt molestie, augue turpis dictum risus, sit amet sodales diam mauris vitae diam. Maecenas id mattis sapien, sed dictum lorem. Suspendisse malesuada vel nisl nec semper. Suspendisse pellentesque fermentum massa, vel maximus arcu gravida vel. Nullam sodales metus non diam commodo vulputate. Cras porta rhoncus lacus. Phasellus sit amet risus at diam dignissim suscipit. Integer convallis turpis quis est mollis, et efficitur est sagittis. Cras laoreet bibendum felis eu rutrum. Quisque consequat sollicitudin tellus, vel cursus elit ornare vitae.<br /><br />
      Suspendisse id porta tellus, eget luctus nisl. Mauris viverra consectetur scelerisque. Mauris gravida velit pulvinar, cursus nunc porta, molestie sapien. Duis pharetra odio et fringilla aliquet. Nulla blandit lectus a metus facilisis, sed gravida tortor consectetur. Morbi facilisis sed sem ut malesuada. Sed quis ullamcorper arcu. Integer rhoncus lorem sodales, sagittis mi a, accumsan turpis. Aliquam eleifend eleifend ornare. Sed elementum, libero fringilla volutpat molestie, tellus lacus sodales massa, at facilisis diam metus a lacus. Mauris non convallis orci. Nam sit amet leo odio. Nullam id consequat mi, cursus commodo arcu. Nunc sed elit vitae est tincidunt elementum.<br /><br />
      Fusce dignissim eros lacus, vel vestibulum arcu sagittis vel. Nullam eget tortor nec orci faucibus lacinia. In venenatis sem eget sem maximus dignissim. Cras dignissim eu sapien eget porttitor. In blandit nibh nec dolor rutrum sagittis. Phasellus maximus egestas facilisis. Morbi quis neque sit amet odio tincidunt blandit.<br /><br />
      Vestibulum imperdiet non velit in imperdiet. Aliquam consequat est quis mauris bibendum consectetur. Pellentesque convallis et quam ut imperdiet. Nullam tristique pellentesque scelerisque. In convallis lectus non risus ornare, sit amet egestas ipsum vulputate. Curabitur eros ligula, tempus eget vehicula a, malesuada ac ipsum. Vivamus pulvinar lectus tellus, eu pellentesque elit tincidunt id. Vivamus varius nibh cursus ipsum lacinia, eget cursus quam faucibus. Phasellus in nisl vitae metus dignissim semper. Etiam molestie, augue ut vestibulum sollicitudin, lorem leo auctor lectus, nec rhoncus neque tortor ac nisi. Vivamus at finibus augue, facilisis tempor odio. Curabitur nisi quam, dictum sit amet arcu non, semper dignissim dui.<br /><br />
      Sed id maximus enim. Mauris pretium pharetra arcu, eu maximus sapien auctor id. Mauris hendrerit tellus in purus volutpat laoreet. Donec sed ligula eu dolor varius consequat. Maecenas justo mauris, pulvinar quis interdum et, congue quis sapien. Vivamus porta libero risus. Morbi at ultrices ligula. Sed quis velit est. Mauris efficitur massa vitae ipsum imperdiet, sit amet hendrerit dui sagittis. Proin vitae ultrices dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed aliquam velit ut nisl tincidunt luctus. Curabitur elit justo, gravida mollis aliquam sit amet, pharetra nec turpis. Vestibulum eu cursus magna. Pellentesque sagittis interdum velit, id congue elit sagittis sit amet.<br /><br />
      Mauris vel neque vestibulum, molestie dui sed, tempor magna. Vestibulum interdum accumsan erat ut faucibus. Donec consectetur lacinia urna, id molestie magna porttitor in. Maecenas dignissim ante sed massa aliquet, lobortis scelerisque mauris tempor. Suspendisse nulla mi, eleifend at massa vitae, aliquet commodo velit. Proin egestas imperdiet diam, venenatis gravida justo pulvinar id. Sed sit amet sem id nulla rutrum pretium. Etiam id ipsum aliquam felis iaculis luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer ultricies vitae turpis vitae auctor. Duis pulvinar velit sed lacinia tincidunt.<br /><br />
    </div>
  );
}

const Author = ({ post }) => {
  return (
    <div className="post-author-wrapper">
      <div className="post-author">
        
      </div>
    </div>
  )
}

const PostBody = ({ post }) => {
  return (
    <div>
      <div className="post-body">
        <div className="post-column-left">
          <div className="post-social-wrapper" uk-sticky="offset: 200">
            <div className="post-social-items">

            </div>
          </div>
        </div>
        <div className="post-column-center">
          <Breadcrumbs />
          <Meta />
          <Body />
        </div>
        <div className="post-column-right">
          <Author post={post} />
        </div>
      </div>
      <Footer />
    </div>
  )
}

const Posts = ({ post }) => {

  const seo = {
    metaTitle: post.attributes.title,
    metaDescription: post.attributes.description,
    shareImage: post.attributes.cover,
    article: true,
  }

  return (
    <Layout>
      <Seo seo={seo} />
      <Cover post={post} image={post.attributes.cover} />
      <PostBody post={post} />
    </Layout>
  )
}

export async function getStaticPaths() {
  const postRes = await fetchAPI("/posts", { fields: ["slug"] })

  return {
    paths: postRes.data.map((post) => ({
      params: {
        slug: post.attributes.slug,
      },
    })),
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const postRes = await fetchAPI("/posts", {
    filters: {
      slug: params.slug,
    },
    populate: "*",
  })

  return {
    props: { post: postRes.data[0] },
    revalidate: 1,
  }
}

export default Posts
